// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7CA2_LpX25NigR7l6QCTxl5kWAvsP320',
    appId: '1:494081190035:web:abc41ea399449e55590566',
    messagingSenderId: '494081190035',
    projectId: 'vitamind-9d46b',
    authDomain: 'vitamind-9d46b.firebaseapp.com',
    storageBucket: 'vitamind-9d46b.firebasestorage.app',
    measurementId: 'G-1PB64YBL7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKX-Li4zQbqVtNy2Iu1eKfyiHjT4LJqVQ',
    appId: '1:494081190035:android:f7382e309cd95d99590566',
    messagingSenderId: '494081190035',
    projectId: 'vitamind-9d46b',
    storageBucket: 'vitamind-9d46b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAfpXU7BP0FqxJh9WV_8YpZDWaSZgi1IM',
    appId: '1:494081190035:ios:5e9dfd8e85489929590566',
    messagingSenderId: '494081190035',
    projectId: 'vitamind-9d46b',
    storageBucket: 'vitamind-9d46b.firebasestorage.app',
    iosBundleId: 'com.elianfigueroa.vitamind',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAfpXU7BP0FqxJh9WV_8YpZDWaSZgi1IM',
    appId: '1:494081190035:ios:5e9dfd8e85489929590566',
    messagingSenderId: '494081190035',
    projectId: 'vitamind-9d46b',
    storageBucket: 'vitamind-9d46b.firebasestorage.app',
    iosBundleId: 'com.elianfigueroa.vitamind',
  );
}
